.class public final Lpv/m$a$i;
.super Lfv/n;
.source "SourceFile"

# interfaces
.implements Lev/a;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lpv/m$a;-><init>(Lpv/m;)V
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = null
.end annotation

.annotation system Ldalvik/annotation/Signature;
    value = {
        "Lfv/n;",
        "Lev/a<",
        "Lvv/e;",
        ">;"
    }
.end annotation


# instance fields
.field public final synthetic a:Lpv/m;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lpv/m<",
            "TT;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Lpv/m;)V
    .locals 0
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lpv/m<",
            "TT;>;)V"
        }
    .end annotation

    iput-object p1, p0, Lpv/m$a$i;->a:Lpv/m;

    const/4 p1, 0x0

    invoke-direct {p0, p1}, Lfv/n;-><init>(I)V

    return-void
.end method


# virtual methods
.method public final invoke()Ljava/lang/Object;
    .locals 4

    sget v0, Lpv/m;->d:I

    iget-object p0, p0, Lpv/m$a$i;->a:Lpv/m;

    invoke-virtual {p0}, Lpv/m;->r()LUv/b;

    move-result-object v0

    iget-object v1, p0, Lpv/m;->c:Lpv/Y$b;

    invoke-virtual {v1}, Lpv/Y$b;->invoke()Ljava/lang/Object;

    move-result-object v1

    check-cast v1, Lpv/m$a;

    invoke-virtual {v1}, Ljava/lang/Object;->getClass()Ljava/lang/Class;

    sget-object v2, Lpv/r$a;->b:[Lmv/j;

    const/4 v3, 0x0

    aget-object v2, v2, v3

    iget-object v1, v1, Lpv/r$a;->a:Lpv/Y$a;

    invoke-virtual {v1}, Lpv/Y$a;->invoke()Ljava/lang/Object;

    move-result-object v1

    const-string v2, "<get-moduleData>(...)"

    invoke-static {v1, v2}, Lfv/l;->g(Ljava/lang/Object;Ljava/lang/String;)V

    check-cast v1, LAv/j;

    iget-boolean v2, v0, LUv/b;->c:Z

    iget-object v1, v1, LAv/j;->a:Lhw/k;

    if-eqz v2, :cond_0

    invoke-virtual {v1, v0}, Lhw/k;->b(LUv/b;)Lvv/e;

    move-result-object v0

    goto :goto_0

    :cond_0
    iget-object v1, v1, Lhw/k;->b:Lvv/B;

    invoke-static {v1, v0}, Lvv/t;->a(Lvv/B;LUv/b;)Lvv/e;

    move-result-object v0

    :goto_0
    if-nez v0, :cond_3

    iget-object p0, p0, Lpv/m;->b:Ljava/lang/Class;

    invoke-static {p0}, LAv/f$a;->a(Ljava/lang/Class;)LAv/f;

    move-result-object v0

    if-eqz v0, :cond_1

    iget-object v0, v0, LAv/f;->b:LOv/a;

    if-eqz v0, :cond_1

    iget-object v0, v0, LOv/a;->a:LOv/a$a;

    goto :goto_1

    :cond_1
    const/4 v0, 0x0

    :goto_1
    if-nez v0, :cond_2

    const/4 v1, -0x1

    goto :goto_2

    :cond_2
    sget-object v1, Lpv/m$b;->a:[I

    invoke-virtual {v0}, Ljava/lang/Enum;->ordinal()I

    move-result v2

    aget v1, v1, v2

    :goto_2
    packed-switch v1, :pswitch_data_0

    :pswitch_0
    new-instance p0, LPu/h;

    invoke-direct {p0}, Ljava/lang/RuntimeException;-><init>()V

    throw p0

    :pswitch_1
    new-instance v1, Lpv/W;

    new-instance v2, Ljava/lang/StringBuilder;

    const-string v3, "Unknown class: "

    invoke-direct {v2, v3}, Ljava/lang/StringBuilder;-><init>(Ljava/lang/String;)V

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const-string p0, " (kind = "

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    const/16 p0, 0x29

    invoke-virtual {v2, p0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object p0

    invoke-direct {v1, p0}, Lpv/W;-><init>(Ljava/lang/String;)V

    throw v1

    :pswitch_2
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It\'s not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "

    invoke-static {p0, v1}, LCb/p;->a(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_3
    new-instance v0, Ljava/lang/UnsupportedOperationException;

    const-string v1, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "

    invoke-static {p0, v1}, LCb/p;->a(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Ljava/lang/UnsupportedOperationException;-><init>(Ljava/lang/String;)V

    throw v0

    :pswitch_4
    new-instance v0, Lpv/W;

    const-string v1, "Unresolved class: "

    invoke-static {p0, v1}, LCb/p;->a(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/String;

    move-result-object p0

    invoke-direct {v0, p0}, Lpv/W;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_3
    return-object v0

    nop

    :pswitch_data_0
    .packed-switch -0x1
        :pswitch_4
        :pswitch_0
        :pswitch_3
        :pswitch_3
        :pswitch_3
        :pswitch_2
        :pswitch_1
        :pswitch_4
    .end packed-switch
.end method
